[package]
name = "kirapo-descrambler-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.9"
regex = "1.12.2"
reqwest = { version = "0.12.24", features = ["blocking"] }
serde = "1.0.228"
serde_json = "1.0.145"
